In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
file_path = 'loan_sanction_test.csv'

In [5]:
df = pd.read_csv(file_path)

In [9]:
df.Education

0          Graduate
1          Graduate
2          Graduate
3          Graduate
4      Not Graduate
           ...
362    Not Graduate
363        Graduate
364        Graduate
365        Graduate
366        Graduate
Name: Education, Length: 367, dtype: object

In [10]:
df.Education.value_counts()

Education
Graduate        283
Not Graduate     84
Name: count, dtype: int64

In [11]:
df.Property_Area

0          Urban
1          Urban
2          Urban
3          Urban
4          Urban
         ...
362        Urban
363        Urban
364    Semiurban
365        Rural
366        Rural
Name: Property_Area, Length: 367, dtype: object

In [12]:
df.Property_Area.value_counts()

Property_Area
Urban        140
Semiurban    116
Rural        111
Name: count, dtype: int64

In [13]:
df.Gender

0      Male
1      Male
2      Male
3      Male
4      Male
       ...
362    Male
363    Male
364    Male
365    Male
366    Male
Name: Gender, Length: 367, dtype: object

In [14]:
df.Gender.value_counts()

Gender
Male      286
Female     70
Name: count, dtype: int64

In [15]:
df.ApplicantIncome

0      5720
1      3076
2      5000
3      2340
4      3276
       ...
362    4009
363    4158
364    3250
365    5000
366    9200
Name: ApplicantIncome, Length: 367, dtype: int64

In [16]:
df.ApplicantIncome.value_counts()

ApplicantIncome
5000    6
3500    6
3333    5
2500    4
7500    4
       ..
2922    1
4082    1
4523    1
4513    1
2333    1
Name: count, Length: 314, dtype: int64

In [29]:
max = df['ApplicantIncome'].max()
min = df['ApplicantIncome'].min()
intervalo = (max - min) / 5

print(f"Tamanho: {intervalo:.2f}")

Tamanho: 14505.80

In [32]:
bucket = [
    min,
    min + intervalo,
    min + 2 * intervalo,
    min + 3 * intervalo,
    min + 4 * intervalo,
    max
]

print(f"Cortes", bucket)

Cortes [0, 14505.8, 29011.6, 43517.399999999994, 58023.2, 72529]